[project]
name = "vibrant"
version = "0.3.1"
description = "Role management discord based on color."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "py-cord>=2.4.1",
    "pillow>=9.5.0",
    "pymongo>=4.3.3",
]
